steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'cloud-build'
  args: [ 'build', '--tag', 'gcr.io/$PROJECT_ID/gcp-iac-project', '.' ]
  env:
  - 'MESSAGE=Hello World From GCP'

substitutions:
  _TAG: $SHORT_SHA

images:
- 'gcr.io/$PROJECT_ID/gcp-iac-project:${_TAG}'
- 'gcr.io/$PROJECT_ID/gcp-iac-project:latest'

tags: []

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 300s
